### ISSUE TITLE
Names of individuals

### ISSUE THREAD

**Issue by ashotmarg** [YingZhou001/IBDkin#4]
Hi Ying,

Thanks a lot for this tool which seems exactly what I need to convert the IBD output data (from hap-ibd) into relatedness estimates.
Could you please elaborate if there are any limitations for the names of individuals in the "ind.txt" and "*ibd.gz" files? 

The reason I am asking is that when running IBDkin I am getting "Segmentation fault (core dumped)" error. However when I change all the names into a more simple names e.g., sample{1..367} it works properly.
__________________________________
allocate IBD buffer
read_genetic_map() Time = 0.024s
367 individuals
read_ind() Time = 0.001s

First pass ...
        reading all.chr21.hapIBD.ibd.gz
Segmentation fault (core dumped)
...
__________________________________

The sample names I have are fairly long (e.g., 70 characters long) with underscores and dashes, such as: 89plfsysv-22SPG0056717-03_167898426660-Tissue-WWS_v2-PO45GHRX2-NNBD87788

Thanks,
Ashot

**Comment by YingZhou001** [comment]
Hi Ashot

Thanks for reaching out.
Yes, IBDkin has an issue with long sample ids. I will find a time release
an updated version for this issue.

Best,
Ying

**Comment by ashotmarg** [comment]
Thanks Ying, it would be great!

**Comment by YingZhou001** [comment]
Hi Ashot,

Please use the updated version 2.8.7.8, and try to modify the "head.h"


#define BUFF_id 32 //for ID/Chr string length ---> increase 32 to a number larger than your maximum ID string length
#define BUFF_col 2048 //should larger than BUFF_id*2+1024 ----> increase this, too.
#define BUFF_row 1048576 //BUFF_col * BUFF_row * 2  determine mem in use  ---> decrease this number if your machine memory is not large

Let me know if this bug is not fixed.

Thanks,
Ying

**Comment by ashotmarg** [comment]
Hi Ying, thanks a lot for the new version, works great!
Just so you know, the welcome section still says v2.8.7.7 :)
___________________
############################
#Welcome to IBDkin V2.8.7.7#
############################
Copyright (C) 2020 Ying Zhou
___________________

Thanks,
Ashot

**Comment by YingZhou001** [comment]
Updated, thanks a lot!
